apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  ports:
  - name: data
    port: 20
    targetPort: 20
  - name: ftps
    protocol: TCP
    port: 21
    targetPort: 21
  - name: ftps-pasv
    protocol: TCP
    port: 30000
    targetPort: 30000
  selector:
    app: ftps
  type: LoadBalancer
  # loadBalancerIP: 192.168.49.54

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps-container
        image: my_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 30000