apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  ports:
  - name: phpmyadmin
    protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.49.52

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: my_phpmyadmin
        imagePullPolicy: Never

