FROM	alpine

RUN		mkdir -p /run/nginx
RUN		apk add nginx openssh openssl --allow-untrusted --no-cache
RUN		apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache

RUN		echo "root:toor" | chpasswd
RUN		openssl req -x509 -nodes -days 365 \
		-newkey rsa:2048 -subj '/C=US/ST=CA/L=LA/O=42/CN=secullod' \
		-keyout /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt

RUN		ssh-keygen -A

COPY	/srcs/sshd_config			/etc/ssh/
COPY	/srcs/telegraf.conf			/etc/telegraf/
COPY	/srcs/nginx.conf			/etc/nginx/
COPY	/srcs/start.sh				/

EXPOSE	80 443 22

ENTRYPOINT	sh start.sh