FROM	alpine

RUN 	mkdir -p /run/nginx
RUN		apk add wget nginx php7 php7-fpm php7-mysqli php7-mbstring php7-json php7-session
RUN		apk add telegraf --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted --no-cache

RUN		mkdir -p /var/www/ && cd /var/www/
RUN		wget https://wordpress.org/latest.tar.gz && tar -xzvf latest.tar.gz && rm latest.tar.gz && \
		mv /wordpress /var/www/

RUN     chown nginx:nginx -R /var/www/wordpress

COPY	/srcs/telegraf.conf		/etc/telegraf/
COPY	/srcs/wp-config.php		/var/www/wordpress/
COPY	/srcs/start.sh			/
COPY    /srcs/nginx.conf		/etc/nginx/conf.d/default.conf

EXPOSE	5050

ENTRYPOINT sh start.sh
